### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mirzazulfan** [hufan-akari/music163diff#1]
Hi @hufan-akari .. I designed a logo for your project. If you like it, you can use it. I will send you files. free for your project.
![music](https://user-images.githubusercontent.com/36124339/38666016-1f611232-3e68-11e8-9855-259bc4406b1f.png)

Best Regard.

**Comment by magic-akari** [comment]
This repo is a tool for personal use rather than a music player.
It makes no sense to get a logo. 
Sorry for closing the issue.
